openapi: 3.0.2

################################################################################
#                              API Information                                 #
################################################################################
info:
  title: jrc-node server api spec
  description: "OpenAPI specification for the blockchain server backend for jrc-node"
  license:
    name: MIT
    url: https://opensource.org/licenses/mit-license.php
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Full Documentation
  url: https://github.com/jounaidr/jrc-node

################################################################################
#                           API Endpoint Definitions                           #
################################################################################
paths:
### Blockchain ###
  /blockchain:
    get:
      summary: Get the full blockchain
      operationId: getBlockchain
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blockchain'

  /blockchain/lastblock:
    get:
      summary: Get the last block in the blockchain
      operationId: getLastBlock
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'

  /blockchain/addblock:
    post:
      summary: Attempt to add a new block to the blockchain
      operationId: addBlock
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        400:
          description: block is not valid
          content:
            application/json:
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Block'
        description: Block to be added
        required: true

  /blockchain/size:
    get:
      summary: Get the blockchain length
      operationId: getBlockchainSize
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: integer

################################################################################
#                             Model Definitions                                #
################################################################################
components:
  schemas:
    Blockchain:
      type: array
      items:
        $ref: '#/components/schemas/Block'

    Block:
      type: object
      properties:
        hash:
          type: string
        previousHash:
          type: string
        data:
          type: string
        timeStamp:
          type: string
        nonce:
          type: string
        difficulty:
          type: string
        proofOfWork:
          type: string