version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - store_artifacts:
          path: /home/circleci/project/target/surefire-reports/
          destination: test-results
