version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  upload_results:
    working_directory: /tmp
    jobs:
      - store_artifacts:
          path: /tmp/artifacts
