version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
       docker:
          # specify the version you desire here
          - image: circleci/openjdk:11
        steps:
          - maven/test # checkout, build, test, and upload test results
